spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: sa
    password:
  h2.console.enabled: true

#  security:
#    user:
#      name: user
#      password: password
#      roles: USER

  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  cache:
    cache-names: restaurants
    caffeine.spec: maximumSize=1,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.github.graschenko: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#    org.springframework.security.web.filterchainproxy: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
